spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/test?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    properties.hibernate.connection.characterEncoding: utf-8
    properties.hibernate.connection.CharSet: utf-8
    properties.hibernate.connection.useUnicode: true
    hibernate.ddl-auto: validate
