create table comment (comment_id integer generated by default as identity, content varchar(255), reg_date timestamp, document_id integer, user_id varchar(255), primary key (comment_id));
INSERT INTO comment (comment_id, content, reg_date, document_id, user_id) VALUES ('comment1', CURRENT_TIMESTAMP(), 1, 'userId1');
