create table customer (id integer generated by default as identity, first_name varchar(255), last_name varchar(255), primary key (id));
INSERT INTO customers (first_name, last_name) VALUES ('Nobita', 'Nobi');
INSERT INTO customers (first_name, last_name) VALUES ('Takeshi', 'Goda');
INSERT INTO customers (first_name, last_name) VALUES ('Suneo', 'Honekawa');
INSERT INTO customers (first_name, last_name) VALUES ('Shizuka', 'Minamoto');
